<!--
	Same text as before, given the structure it was missing: the document was a
	single run of unwrapped lines, so headings and the principles list did not
	render as headings or a list.
-->
<article class="shell max-w-3xl py-16">
	<header class="border-b border-[var(--rule)] pb-8">
		<span class="eyebrow">Legal</span>
		<h1 class="mt-3 text-4xl font-semibold">Privacy Policy</h1>
		<p class="meta mt-4">Effective as of Jul 12, 2025 · Updated Jul 12, 2025</p>
	</header>

	<div class="mt-10 space-y-10">
		<section>
			<h2 class="text-lg font-semibold">Introduction and Definition</h2>
			<p class="mt-3 text-sm leading-relaxed text-[var(--text-dim)]">
				This Privacy Policy sets out how we, Bruce Devices, use and protect your personal data that you provide to us, or that is otherwise obtained
				or generated by us, in connection with your use of Bruce App (the “Services”). For the purposes of this Privacy Policy, ‘we’, ‘us’ and ‘our’
				refers to Bruce Devices, and ‘you’ refers to you, the user of the Services.
			</p>
		</section>

		<section>
			<h2 class="text-lg font-semibold">Principles</h2>
			<p class="mt-3 text-sm leading-relaxed text-[var(--text-dim)]">We follow simple principles when it comes to your data:</p>
			<ul class="mt-4 space-y-3">
				<li class="flex items-start gap-3 text-sm leading-relaxed text-[var(--text-dim)]">
					<span class="mt-[0.55rem] h-px w-4 shrink-0 bg-[var(--rule-strong)]"></span>
					<span>Your data is used exactly as you expect</span>
				</li>
				<li class="flex items-start gap-3 text-sm leading-relaxed text-[var(--text-dim)]">
					<span class="mt-[0.55rem] h-px w-4 shrink-0 bg-[var(--rule-strong)]"></span>
					<span>Your data is not shared with anyone, at any time</span>
				</li>
				<li class="flex items-start gap-3 text-sm leading-relaxed text-[var(--text-dim)]">
					<span class="mt-[0.55rem] h-px w-4 shrink-0 bg-[var(--rule-strong)]"></span>
					<span>Your data does not leave your device without your explicit consent</span>
				</li>
			</ul>
		</section>

		<section>
			<h2 class="text-lg font-semibold">Information you provide</h2>
			<p class="mt-3 text-sm leading-relaxed text-[var(--text-dim)]">
				<strong class="text-white">Installed Apps.</strong> Bruce App requires accesses to all applications installed on your device in order to function.
				This information is originally accessed through the Android system, and may be stored on-device in order to allow customization of app features.
				This information is only used on-device, and is not shared with any third-party. If you choose to share a bug report, you may choose to send a list
				of your apps and some metadata to us. This information will only be used to diagnose and fix problems.
			</p>
			<p class="mt-4 text-sm leading-relaxed text-[var(--text-dim)]">
				<strong class="text-white">Managing your information.</strong> All information used by Bruce App is stored on-device, and can be managed through
				Bruce App application Settings, or through Android’s system controls.
			</p>
		</section>

		<section>
			<h2 class="text-lg font-semibold">How we share your information</h2>
			<p class="mt-3 text-sm leading-relaxed text-[var(--text-dim)]">We do not share any information at any time.</p>
		</section>

		<section>
			<h2 class="text-lg font-semibold">Updates</h2>
			<p class="mt-3 text-sm leading-relaxed text-[var(--text-dim)]">
				This privacy policy will be updated as needed so that it is accurate, current, and clear.
			</p>
		</section>

		<section>
			<h2 class="text-lg font-semibold">Contact Us</h2>
			<p class="mt-3 text-sm leading-relaxed text-[var(--text-dim)]">
				If you have questions about this Privacy Policy please contact <a href="mailto:contact@bruce.computer">contact@bruce.computer</a>.
			</p>
		</section>
	</div>
</article>
