#!/usr/bin/env python3
"""
Bruce Build Tool (bbt) — v1.0
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
A standalone Python build system for Bruce firmware applications (.bruce).
Inspired by Flipper Zero's ufbt/FAM workflow.

Features:
  * Parses application.bam (JSON manifest)
  * Compiles static PNG/BMP images into C arrays (RGB565)
  * Discovers all .c/.cpp sources (including third-party libs)
  * Invokes xtensa-esp32-elf-gcc directly (no PlatformIO required)
  * Packs the final ELF into a .bruce package with BapHeader

Usage:
    python bbt.py build                  # Build app in current directory
    python bbt.py build --arch esp32s3   # Build for ESP32-S3
    python bbt.py clean                  # Remove build artifacts
    python bbt.py create <appid>         # Scaffold a new app project

Requirements:
    * xtensa-esp32-elf toolchain in PATH (or xtensa-esp32s3-elf for S3)
    * Python 3.10+
    * Pillow (pip install Pillow) — only needed if you have image assets
"""

import argparse
import json
import os
import struct
import subprocess
import shutil
import sys
from pathlib import Path

# ═══════════════════════════════════════════════════════════════════════════════
# Constants
# ═══════════════════════════════════════════════════════════════════════════════

BAP_MAGIC = b"BAP1"
BAP_HEADER_SIZE = 42  # 4 magic + 1 arch + 1 version + 32 name + 4 elf_size

ARCH_MAP = {
    "esp32":   {"id": 0x01, "prefix": "xtensa-esp32-elf"},
    "esp32s3": {"id": 0x02, "prefix": "xtensa-esp32s3-elf"},
}

# Compiler flags for position-independent code
CFLAGS = [
    "-fPIC", "-mlongcalls", "-Os",
    "-ffunction-sections", "-fdata-sections",
    "-nostdlib", "-fno-exceptions",
    "-std=gnu11",
]

CXXFLAGS = [
    "-fPIC", "-mlongcalls", "-Os",
    "-ffunction-sections", "-fdata-sections",
    "-nostdlib", "-fno-exceptions", "-fno-rtti",
    "-std=gnu++17",
]

LDFLAGS = [
    "-nostdlib", "-shared",
    "-Wl,--gc-sections",
    "-Wl,--no-undefined",
]

# ═══════════════════════════════════════════════════════════════════════════════
# Manifest
# ═══════════════════════════════════════════════════════════════════════════════

REQUIRED_MANIFEST_FIELDS = ["appid", "name", "version", "entry_point", "author"]

def load_manifest(app_dir: Path) -> dict:
    """Load and validate application.bam (JSON)."""
    manifest_path = app_dir / "application.bam"
    if not manifest_path.is_file():
        fatal(f"Manifest not found: {manifest_path}\n"
              f"Run 'bbt.py create <appid>' to scaffold a new project.")
    with open(manifest_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    for key in REQUIRED_MANIFEST_FIELDS:
        if key not in data:
            fatal(f"Manifest missing required field: '{key}'")
    return data


# ═══════════════════════════════════════════════════════════════════════════════
# Asset Compiler
# ═══════════════════════════════════════════════════════════════════════════════

def compile_assets(assets_dir: Path, out_dir: Path) -> list[Path]:
    """Convert PNG/BMP images to C source/header (RGB565).

    Returns a list of generated source file paths.
    """
    try:
        from PIL import Image
    except ImportError:
        fatal("Pillow is required for asset compilation.\n"
              "Install it with: pip install Pillow")

    out_dir.mkdir(parents=True, exist_ok=True)
    header_path = out_dir / "bruce_assets.h"
    source_path = out_dir / "bruce_assets.c"

    image_files = list(assets_dir.rglob("*.png")) + list(assets_dir.rglob("*.bmp"))
    if not image_files:
        info("No image assets found — generating empty stubs.")
        _write_empty_assets(header_path, source_path)
        return [source_path]

    with open(header_path, "w", encoding="utf-8") as h, \
         open(source_path, "w", encoding="utf-8") as c:

        h.write("// Auto-generated by bbt.py — DO NOT EDIT\n")
        h.write("#pragma once\n\n")
        h.write("#include <stdint.h>\n\n")
        h.write("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n")

        c.write("// Auto-generated by bbt.py — DO NOT EDIT\n")
        c.write("#include \"bruce_assets.h\"\n\n")

        for img_path in sorted(image_files):
            name = _sanitize_name(img_path.stem)
            info(f"  Asset: {img_path.name} → {name} (RGB565)")

            img = Image.open(img_path).convert("RGB")
            w, h_px = img.size

            # Declarations
            h.write(f"// {img_path.name} ({w}x{h_px})\n")
            h.write(f"extern const uint16_t {name}_data[];\n")
            h.write(f"#define {name}_width  {w}\n")
            h.write(f"#define {name}_height {h_px}\n\n")

            # Data array
            pixels = _image_to_rgb565(img)
            c.write(f"// {img_path.name} ({w}x{h_px}, {len(pixels)*2} bytes)\n")
            c.write(f"const uint16_t {name}_data[] = {{\n")
            for row_start in range(0, len(pixels), 16):
                row = pixels[row_start:row_start+16]
                c.write("    " + ", ".join(f"0x{v:04X}" for v in row) + ",\n")
            c.write("};\n\n")

        h.write("#ifdef __cplusplus\n}\n#endif\n")

    info(f"Assets compiled: {len(image_files)} image(s)")
    return [source_path]


def _image_to_rgb565(img) -> list[int]:
    """Convert a PIL Image (RGB mode) to a list of RGB565 uint16 values."""
    pixels = []
    for y in range(img.height):
        for x in range(img.width):
            r, g, b = img.getpixel((x, y))
            rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
            pixels.append(rgb565)
    return pixels


def _sanitize_name(stem: str) -> str:
    """Convert a filename stem into a valid C identifier."""
    name = stem.replace("-", "_").replace(" ", "_").replace(".", "_")
    if name[0].isdigit():
        name = "_" + name
    return name


def _write_empty_assets(header_path: Path, source_path: Path):
    """Write empty asset stubs so compilation doesn't break."""
    header_path.write_text(
        "// Auto-generated by bbt.py — no assets\n"
        "#pragma once\n\n"
        "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"
        "#ifdef __cplusplus\n}\n#endif\n",
        encoding="utf-8"
    )
    source_path.write_text(
        "// Auto-generated by bbt.py — no assets\n"
        "#include \"bruce_assets.h\"\n",
        encoding="utf-8"
    )


# ═══════════════════════════════════════════════════════════════════════════════
# Compilation
# ═══════════════════════════════════════════════════════════════════════════════

def discover_sources(app_dir: Path, exclude_dirs: set[str] = None) -> list[Path]:
    """Recursively find all .c/.cpp/.cc files, excluding build dirs."""
    exclude = exclude_dirs or {".bbt_build", "dist", ".git", "__pycache__"}
    sources = []
    for ext in ("*.c", "*.cpp", "*.cc", "*.cxx"):
        for p in app_dir.rglob(ext):
            if not any(part in exclude for part in p.parts):
                sources.append(p)
    return sources


def compile_sources(sources: list[Path], include_dirs: list[Path],
                    build_dir: Path, arch: str, linker_script: Path) -> Path:
    """Compile all sources and link into a shared ELF.

    Returns the path to the output ELF file.
    """
    arch_info = ARCH_MAP[arch]
    gcc = f"{arch_info['prefix']}-gcc"
    gpp = f"{arch_info['prefix']}-g++"

    build_dir.mkdir(parents=True, exist_ok=True)
    obj_files = []

    # Include flags
    inc_flags = []
    for d in include_dirs:
        inc_flags += ["-I", str(d)]

    # --- Compile each source ---
    for src in sources:
        obj = build_dir / (src.stem + ".o")
        is_cpp = src.suffix in (".cpp", ".cc", ".cxx")
        compiler = gpp if is_cpp else gcc
        flags = CXXFLAGS if is_cpp else CFLAGS

        cmd = [compiler] + flags + inc_flags + ["-c", str(src), "-o", str(obj)]
        info(f"  CC  {src.name}")
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            fatal(f"Compilation failed for {src.name}:\n{result.stderr}")
        obj_files.append(obj)

    # --- Link ---
    elf_path = build_dir / "app.elf"
    ld_cmd = [gcc] + LDFLAGS
    if linker_script and linker_script.is_file():
        ld_cmd += ["-T", str(linker_script)]
    ld_cmd += [str(o) for o in obj_files]
    ld_cmd += ["-o", str(elf_path)]

    info(f"  LD  app.elf")
    result = subprocess.run(ld_cmd, capture_output=True, text=True)
    if result.returncode != 0:
        fatal(f"Linking failed:\n{result.stderr}")

    elf_size = elf_path.stat().st_size
    info(f"  ELF size: {elf_size} bytes")
    return elf_path


# ═══════════════════════════════════════════════════════════════════════════════
# Packing (.bruce)
# ═══════════════════════════════════════════════════════════════════════════════

def pack_bruce(elf_path: Path, manifest: dict, arch: str, out_dir: Path) -> Path:
    """Create a .bruce file: BapHeader + raw ELF bytes.

    BapHeader layout (packed, 42 bytes):
        char magic[4]     = "BAP1"
        uint8_t arch      = 0x01 (ESP32) or 0x02 (ESP32-S3)
        uint8_t version   = 1
        char name[32]     = app display name (null-padded)
        uint32_t elf_size = size of ELF payload in bytes
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    bruce_path = out_dir / f"{manifest['appid']}.bruce"

    elf_data = elf_path.read_bytes()
    elf_size = len(elf_data)

    # Build header
    arch_id = ARCH_MAP[arch]["id"]
    name_bytes = manifest["name"].encode("utf-8")[:31]
    name_padded = name_bytes.ljust(32, b"\x00")

    header = struct.pack("<4sBB32sI",
        BAP_MAGIC,          # magic[4]
        arch_id,            # arch
        1,                  # BAP format version
        name_padded,        # name[32]
        elf_size            # elf_size
    )

    with open(bruce_path, "wb") as f:
        f.write(header)
        f.write(elf_data)

    total_size = BAP_HEADER_SIZE + elf_size
    info(f"Package created: {bruce_path.name} ({total_size} bytes)")
    return bruce_path


# ═══════════════════════════════════════════════════════════════════════════════
# Scaffold (create new project)
# ═══════════════════════════════════════════════════════════════════════════════

def scaffold_project(appid: str, target_dir: Path):
    """Create a new app project skeleton."""
    app_dir = target_dir / appid
    if app_dir.exists():
        fatal(f"Directory already exists: {app_dir}")

    app_dir.mkdir(parents=True)
    (app_dir / "assets").mkdir()

    # Manifest
    manifest = {
        "appid": appid,
        "name": appid.replace("_", " ").title(),
        "version": "1.0",
        "author": "Your Name",
        "entry_point": "app_main",
        "assets_dir": "assets"
    }
    (app_dir / "application.bam").write_text(
        json.dumps(manifest, indent=4, ensure_ascii=False),
        encoding="utf-8"
    )

    # Main source
    (app_dir / "app.c").write_text(
        '#include "bruce_api.h"\n'
        '#include "bruce_assets.h"\n'
        "\n"
        "void app_main(BruceAPI* api) {\n"
        "    if (!api) return;\n"
        "\n"
        '    api->clear_screen(0x0000);\n'
        f'    api->draw_main_border_with_title("{manifest["name"]}");\n'
        '    api->draw_string("Hello from my app!", 20, 60, 0xFFFF);\n'
        "\n"
        "    while (1) {\n"
        "        if (api->check_escape_press()) break;\n"
        "        api->bruce_delay(50);\n"
        "    }\n"
        "}\n",
        encoding="utf-8"
    )

    info(f"Project created: {app_dir}")
    info(f"  Edit {appid}/app.c and run: python bbt.py build")


# ═══════════════════════════════════════════════════════════════════════════════
# Logging helpers
# ═══════════════════════════════════════════════════════════════════════════════

def info(msg: str):
    print(f"[bbt] {msg}")

def fatal(msg: str):
    sys.stderr.write(f"[bbt] ERROR: {msg}\n")
    sys.exit(1)


# ═══════════════════════════════════════════════════════════════════════════════
# Main
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        prog="bbt",
        description="Bruce Build Tool — build and package .bruce applications"
    )
    sub = parser.add_subparsers(dest="command", required=True)

    # --- build ---
    p_build = sub.add_parser("build", help="Build the app in the current directory")
    p_build.add_argument("--arch", choices=["esp32", "esp32s3"], default="esp32",
                         help="Target architecture (default: esp32)")
    p_build.add_argument("--sdk", type=str, default=None,
                         help="Path to bruce SDK include directory (auto-detected)")

    # --- clean ---
    sub.add_parser("clean", help="Remove build artifacts")

    # --- create ---
    p_create = sub.add_parser("create", help="Scaffold a new app project")
    p_create.add_argument("appid", help="Application ID (e.g. my_cool_app)")

    args = parser.parse_args()

    if args.command == "clean":
        for d in [".bbt_build", "dist"]:
            p = Path.cwd() / d
            if p.exists():
                shutil.rmtree(p)
                info(f"Removed {d}/")
        sys.exit(0)

    if args.command == "create":
        scaffold_project(args.appid, Path.cwd())
        sys.exit(0)

    # ── build ──────────────────────────────────────────────────────────────
    app_dir = Path.cwd()
    build_dir = app_dir / ".bbt_build"

    # 1. Manifest
    info("=== Step 1: Reading manifest ===")
    manifest = load_manifest(app_dir)
    info(f"  App: {manifest['name']} v{manifest['version']} by {manifest['author']}")

    # 2. Assets
    info("=== Step 2: Compiling assets ===")
    assets_dir = app_dir / manifest.get("assets_dir", "assets")
    asset_sources = compile_assets(assets_dir, build_dir)

    # 3. Discover sources
    info("=== Step 3: Discovering sources ===")
    app_sources = discover_sources(app_dir)
    all_sources = app_sources + asset_sources
    info(f"  Found {len(app_sources)} app source(s) + {len(asset_sources)} asset source(s)")

    # 4. Resolve SDK include path
    sdk_include = None
    if args.sdk:
        sdk_include = Path(args.sdk)
    else:
        # Auto-detect: look for bruce_api.h relative to bbt.py location
        bbt_dir = Path(__file__).resolve().parent
        candidates = [
            bbt_dir / "include",                   # firmware/include
            bbt_dir.parent / "firmware" / "include",
        ]
        for c in candidates:
            if (c / "bruce_api.h").is_file():
                sdk_include = c
                break
    if not sdk_include or not sdk_include.is_dir():
        fatal("Cannot find Bruce SDK (bruce_api.h). Use --sdk /path/to/include")

    include_dirs = [sdk_include, build_dir, app_dir]

    # 5. Compile & Link
    info("=== Step 4: Compiling & Linking ===")
    linker_script = app_dir / "app.ld"
    elf_path = compile_sources(all_sources, include_dirs, build_dir, args.arch, linker_script)

    # 6. Pack
    info("=== Step 5: Packing .bruce ===")
    dist_dir = app_dir / "dist"
    bruce_path = pack_bruce(elf_path, manifest, args.arch, dist_dir)

    info("=" * 50)
    info(f"BUILD SUCCESS: {bruce_path}")
    info(f"Copy {bruce_path.name} to your ESP32 SD card / LittleFS.")


if __name__ == "__main__":
    main()
