[env:esp32s3_viking]
extends = env
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.partitions = boards/ESP32S3-Viking/partitions_16Mb.csv
board_build.arduino.memory_type = opi_opi
build_src_filter =${env.build_src_filter} +<../boards/ESP32S3-Viking>

build_flags =
    ${env.build_flags}
    -DESP32S3_VIKING
    -DUSE_TFT_ESPI=1
    -DUSE_HSPI_PORT=1
    -DUSE_TFT_eSPI_TOUCH
    -DHAS_TOUCH=1
    ;  -DUSE_SD_MMC=1          ; SD card not used
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32-libs/esp32s3/include/fatfs/src
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32-libs/esp32s3/include/fatfs/vfs
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32-libs/esp32s3/include/fatfs/diskio
    -I$PROJECT_PACKAGES_DIR/framework-arduinoespressif32-libs/esp32s3/include/fatfs/**
    -Iboards/ESP32S3-Viking
    -Os
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -DHAS_TOUCH=1
;       -DALLOW_ALL_GPIO_FOR_IR_RF=1
    -DREDRAW_DELAY=1
    ; ESP32-S3-WROOM-1 N16R8 = 8MB OPI PSRAM
     -DBOARD_HAS_PSRAM

lib_deps =
    ${env.lib_deps}

lib_ignore =
    SD
    FFat
