[env:fatalcore]
board = fatalcore
board_build.partitions = custom_16Mb.csv
build_src_filter = ${env.build_src_filter} +<../boards/fatalcore>
build_flags =
	${env.build_flags}
	-Iboards/fatalcore
	-Os
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-D USE_HSPI_PORT=1
	-DDEVICE_NAME='"fatalcore"'

	-DCORE_DEBUG_LEVEL=0

	;Infrared Led default pin and state
	;GPIO 5 and GPIO 4 are excluded: LoRa CS and IRQ
	-DIR_TX_PINS='{{"GPIO 2", 2}, {"GPIO 42", 42}}'
	-DIR_RX_PINS='{{"GPIO 1", 1}, {"GPIO 42", 42}}'
	-DRF_TX_PINS='{{"GPIO 42", 42}}'
	-DRF_RX_PINS='{{"GPIO 42", 42}}'

lib_deps =
	${env.lib_deps}
	adafruit/Adafruit INA219
